#项目启动端口
server:
  port: 8080
#数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auto_paycenter?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#配置mybatis
mybatis:
  mapper-locations: classpath:com/sendinfo/auto/mapper/*.xml
  type-aliases-package: com.sendinfo.auto.entity
  configuration:
    # 开启驼峰
    map-underscore-to-camel-case: true

#sql语句日志打印
logging:
  config: classpath:log.xml
  level:
    com:
      sendinfo:
        mapper: debug
  file:
    path: classpath:com/sendinfo/auto/log.txt

swagger:
  enable: true