#项目启动端口
server:
  port: 8000
#数据源配置
spring:
  datasource:
    url: jdbc:mysql://47.97.229.189:3306/auto_paycenter?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    port: 6379 # Redis服务器连接端口
    timeout: 50000 # 连接超时时间（毫秒）
    password:
    jedis:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 50 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
#配置mybatis
mybatis:
  mapper-locations: classpath:com/sendinfo/auto/mapper/*.xml
  type-aliases-package: com.sendinfo.auto.entity
  configuration:
    # 开启驼峰
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    return-instance-for-empty-row: true

#sql语句日志打印
logging:
  config: classpath:log.xml
  level:
    com:
      sendinfo:
        mapper: debug
  file:
    path: classpath:com/sendinfo/auto/log.txt

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 1440

swagger:
  enable: true